- Dockerfile
- README.md
- app.py
Added README.md with instructions to run
Added app.py with basic StreamLit hello world app
Modified Dockerfile to use standard ENV KEY=VALUE format 
Modified Dockerfile with server port and server address
> StreamLit functionality

- Dockerfile
- environment.yml
Switched from Ubuntu to Python 3.12 base image per instructors request. Updated environment.yml python version to 3.12.
> Switched from Ubuntu to Python base image. Updated python version in environment.

- Dockerfile
- README.md
- environment.yml
README was modified to specify the branch to pull from, and I changed the name of the build/image to itchatbot instead of helloworld
I commented out the `RUN pip install -f requirements.txt` line as it drastically increases the installation time and storage space used. Further details can be found in the issue #8
> Removed currently unneeded requirements + modified README

- Dockerfile
- README.md
- app.py
- requirements.txt
Please check and merge this branch before midnight tonight. It worked on my system and fixes the issues that Dr. Alzahrani had with team 3's code. It includes a change the readme to have the correct image name. It also includes the correct use of the python app.py code that is expected
> modification based on team 3 fix

- README.md
Updated Readme with pull command for instructions.
git pull origin main
> Updated Readme with pull command

- app.py
- removed the text area and submit button
- added the streamlit default functions chat_input() and chat_message()
> UI changes

- app.py
- assets/style.css
Landing page color adjustments
> User interface css changes

- app.py
- assets/style.css
User interface changes combined text box and submit button, aligned text box, and changed chat history format.
> User interface changes

- .streamlit/config.toml
- app.py
- assets/style.css
- added custom theme in order to prevent any future CSS color related issues
- fixed issue #58
> Fixed text scrolling through title (Issue #58) and added custom theme

- documentation.ipynb
> jupyter notebook helloworld

- app.py
changed the emojis in the bot's responses to actual like and dislike buttons
> changed the emojis in the bot's responses to actual like and dislike buttons

- Dockerfile
- README.md
Updated Dockerfile with two new ENV:
- `ENV STREAMLIT_SERVER_BASEURLPATH=/team1`
- `ENV STREAMLIT_SERVER_PORT=5001`
Updated README.md with new testing URL.
Will now load on 127.0.0.1:5001/team1.
Works on Linux VM at custom domain.
SS of running on Linux VM:
> Apache local IP fix,

- app.py
From Dr. Alrzahrani 
Error: Only port 5001 is allowed for use (9/29/2024)
Commented out code that runs the Juypter notebook on port 6001.
` subprocess.run(["jupyter", "notebook", "--ip=0.0.0.0", "--port=6001", "--no-browser", "--allow-root"])`
> Updated app.py for Apache fix

- Dockerfile
Changed Mambaforge to Miniforge
Changed file names for consistency
@Boganabi 
Test this please
> Miniforge Update

- app.py
- added loading animation while the response from the model is loading
> Loading animation change

- RAG.py
- app.py
- requirements.txt
Do not merge yet, as even when initializing the milvus vector_store during startup, we are still creating the vector_store for every response call. If that is fixed, this can be merged.
- refactored the code and added logs
- changed from deprecated langchain library to the latest one (langchain_huggingface)
- initializing the milvus vector_store during the startup
> Initializing the milvus vector_store during the startup

- .github/workflows/docker-image.yml
- Dockerfile
- RAG.py
- app.py
- source is displayed as a link under the chatbot response on the UI.
- retrieving source from the metadata of the chatbot response
**as this branch is created from `Docker-mount-fix`**
> Added source for the chatbot response

- Dockerfile
- README.md
- app.py
Updated the Juypter notebook config to now access the juypter notebook at http://localhost:6001/team1/jupyter per instructors request.
> Updated Apache Juypter notebook config

- RAG.py
- app.py
- assets/style.css
- now saving messages as a dictionary based on a unique `id`, instead of as a list
- added logic to store feedback to `session_state.messages`
- displaying multiple sources
- displaying links as Source 1, Source 2, etc..
- added source to the end of the chatbot response on backend
> Rating icons change & Sources display change

- RAG.py
* Switched our original WebBaseLoader to RecursiveUrlLoader
* Meets standard for CORPUS_SOURCE
* Added CORPUS_SOURCE to RAG.py
* Allows for easy CORPUS changes
* Embedding takes significantly more time now since we are loading ~90 webpages
* Currently no solution since corpus must be dynamically loaded
> RecursiveUrlLoader and CORPUS_SOURCE

- RAG.py
Fixed the error where the sources in the UI are being wrongly numbered
> Source Display Error fix

- Dockerfile
- RAG.py
Added a precheck to the DB to see if it exists before IT download and embed.
@smrchanda877 please verify that this code is correct and the logic makes sense.
> Corpus DB check before embedding

- RAG.py
- app.py
- chatbot_statistics.py
- requirements.txt
- changed the prompt to be more specific about not answering the questions that are not in the provided context
- added `score_threshold` and `k` while creating the retriever to filter out the responses
> Prompt change + Filter responses + common keywords

- Dockerfile
- README.md
* Removed the DockerHub pull and run command
* Added --build-arg command to source build
* Modified Dockerfile to read the build arg and write to ENV file
> Changed installation from source to include build arg for API key

- RAG.py
- app.py
- added temperature as `0` while loading `mistralAI` api to get a consistent response everytime
- changing `keywords` to lowercase before adding them to `common_keywords` table
> added temperature to get consistent response

- app.py
- chatbot_statistics.py
- added another table in the backend to store `performance_metrics`
- added SQA questions from the wiki (**answerable** & **unanswerable**) to the code
- added reset button to reset the `performance_metrics` database
- UI for the stats is not entirely done, but basic skeleton is there
> Confusion matrix implementation

- app.py
Changes:
- `Specificity `and `Sensitivity `appear on top of the sidebar
> added ui changes to stats page

- documentation.ipynb
> Jupyter Documentation

- app.py
- chatbot_statistics.py
- added new SQA questions
- refactored the code to adhere to the coding standards
> added new SQA questions to the confusion matrix check

- app.py
- assets/style.css
- chatbot_statistics.py
- requirements.txt
- added custom CSS for the metrics in the sidebar
- created confusion matrix (table) for displaying `True Positive` `True Negative` `False Positive` `False Negative` values
- fixed a minor bug where we were passing variable instead of tuple while performing SQL injection in the `reset_performance_metrics()` function
- added `pandas` to requirements.txt
> Confusion matrix UI + minor fix for Reset Confusion matrix function

- app.py
- chatbot_statistics.py
- added validation checks for columns when inserting values in columns
- removed redundant expressions such as using "DROP TABLE" and "CREATE TABLE IF NOT EXISTS" in the same function
- changed some function names to increase readability and understandability
- added appropriate documentation in functions wherever necessary
> reformatted the code to adhere to python coding standards

- assets/style.css
Removed extra blank spaces on left and right side of chat history and input textbox as well
> Updated UI Chat Interface(Removed extra blank spaces)

- README.md
- assets/style.css
Added SQA Questions to readme file
> Moving SQA to readme

- README.md
Added link to CSUSB CSE server in Readme file
> Add link to cse server in readme

- README.md
Changed SQA questions in readme into a table with two columns: Answerable, Unanswerable
> Modified SQA into table in Readme

- Dockerfile
Removed NeMo guardrails from Dockerfile
> Removed NeMo guardrails

- RAG.py
- app.py
- chatbot_statistics.py
- requirements.txt
- retriever.py
This pull request includes several important changes to the `RAG.py` and `app.py` files, as well as the addition of a new file `retriever.py`. The changes aim to enhance the functionality of the RAG model, improve the handling of answerable and unanswerable questions, and introduce a custom retriever class for better document retrieval.
* Introduced `ScoredRetriever` for better document retrieval, replacing the previous retriever implementation and adjusting the score threshold and number of documents retrieved. [[1]](diffhunk://#diff-b4d3e9b04b00f176789c5ef0a3760957d6d7cd9dd54da08d55639c0e950ab5a3R21-L24) [[2]](diffhunk://#diff-b4d3e9b04b00f176789c5ef0a3760957d6d7cd9dd54da08d55639c0e950ab5a3L60-L95) [[3]](diffhunk://#diff-83f4c56009800f14621fa48ad83a791ae844d24dfe0b9d197505a0e313de4764R1- …
> added custom retriever to only fetch the most relevant document and removed sources for wrong answers

- app.py
Added link to Confusion matrix
> added link to confusion matrix it will redirect to SQA

- app.py
- assets/style.css
Reverts DrAlzahraniProjects/csusb_fall2024_cse6550_team1#181
Accidentally merged to main. Thought the PR was created to Dev, but it was to main.
> Revert "Add clickable title for Confusion Matrix in sidebar"

- RAG.py
- retriever.py
- Removed `retrieval_chain` from the process as we don't really need it because we are manually searching the `vector_store` using similarity search. We can directly pass the retrieved documents to the `document_chain` to get the response from mistral
- Also, increased the number of documents to be retrieved from similarity search to 5 but even if we retrieve 5, we are still only going to pass the documents with the `similiarity score` greater than the `score_threshold` to the `document_chain`
> removed retreival_chain and directly passing the retrieved documents to document_chain

- Dockerfile
- app.py
- ddos_protection.py
Implemented DDOS protection. Created file `ddos_protection.py` for ddos prevention. limits to 10 questions in a minute and locks user out for 3 minutes.
> Implemented DDOS protection

- app.py
- The bug which appeared on CSE server is due to storing the variable in `os` environment variables.
- Changed that to `session_state`. Now, the bug is fixed
> query running bug fix

- app.py
- ddos_protection.py
Fixed DDOS protection. Fixed #191 by moving `handle_rate_limiting` function call. Also, the user was not being locked out for 3 minutes, added that functionality.
> Fixed DDOS protection.

- README.md
Added quotes around Windows CMD run command to handle spaces in folder path
> Added quotes to Win CMD run command

- README.md
Updated README.md to discard local changes with `git reset --hard'
> Updated README.md to discard local changes

- RAG.py
- app.py
- retriever.py
This PR has these following changes:
- vector store now is created with pymilvus
- we are only updating the changes from the website into the vector store, if the website does not have any new changes, the initialization time is very less
- fetching docs from website and fetching all the docs from the vector store is carried out simultaneously
- changed the chunk size to 500
- search query changed from langchain `similarity_search_with_score` to `pymilvus.Collection.search`
> Implemented vector store initialization through pymilvus

- README.md
- app.py
- SQA unanswerable questions updated to void gray cases.
- Removed unnecessary characters from the user input to achieve optimal results in the confusion matrix.
- Also removed some of the python code standard warnings like mentioned below.
> Sqa gray case fix

- RAG.py
- app.py
- changed 'vector_store_initialized' from session_state to os.environ, so that when we press refresh, just the vector store loads
- Removed duplicates from documents we fetch from webpage before updating them into our vector store
> Enhancements (faster loading when refresh + removed duplicates)

- app.py
- assets/style.css
Color changes for prediction table to match dark and light mode
> UI color changes

- RAG.py
- pre-loading the embedding model when we are in initializing milvus stage. Now, the response is even faster
- added check to see if the message is a greeting message like "hi" , "hello", or "what is your name", to give a static response
> made the response faster and added check for greeting messages

- RAG.py
The majority of the time while initializing is actually getting the documents from the website.
All the other were being done but there were being done so fast that there is no time for it to be shown on UI
So, to keep the illusion of all the steps happening, I added small time delays of 0.3 seconds in between the steps
> added dynamic messages in the UI while milvus is initialized

- app.py
- backend/ddos_protection.py
- requirements.txt
Updated DDOS prevention. Stores user information, request data, and lockout time in a `.json`. User id is a hashed version of their ip. Tried doing cookies and a unique user ID but the Streamlit documentation on cookies is pretty much non existent. Also Updated `app.py` with chat box handling, that if a user asks a question while a query is running, the chatbox will be inaccessible for the user and display `Please wait, a response is currently being generated. You cannot ask a new question yet.` if they try and ask a question while a response being generated. Also, added some error handling if the chatbox gets blocked for the user and a API error occurs.
> DDOS Update with User persistance and user input spam protection

- README.md
- setup.py
Automated script for Docker process. Updated `README.md` with instructions for automated script. Left old instructions as a alternate method.
> Automated script for Docker process

- Dockerfile
- backend/RAG.py
* Updated Dockerfile
* Removed Chrome installation since it errored on Mac
* Updated RAG.py
* Commented out Selenium since it was unneeded now
> Updated Dockerfile and RAG.py to remove Chrome and Selenium
